### ISSUE TITLE
Running omni robot timed

### ISSUE THREAD

**Issue by txvvgnx** [rm-robotics/ev3dev-cpp-template-wrapper#24]
**With blocking:**
Using the OmniRobot library's run timed function with blocking enabled will result in the robot moving in a random direction erratically. The speed also changes suddenly. I suspect this is due to the auto-straghten feature that running timed has. 

**Without blocking:**
The robot does not stop after the time limit is reached. Instead, it only stops after the thread is no longer blocked manually.

**Comment by Eisverygoodletter** [comment]
The robot not stopping without blocking should now be fixed in commit 84c597d .
For the with blocking problem, try changing the value of `OMNI_ADJUST` to smaller numbers in https://github.com/rm-robotics/ev3dev-cpp-template-wrapper/blob/84c597dc632e98c1b84fd5ae19589effce86f443/lib/omnirobot/ev3wrapomnirobot.hpp#L10

**Comment by txvvgnx** [comment]
Fixed
